### ISSUE TITLE
Disable oauth providers in devmode until gotrue supports them

### ISSUE THREAD

**Issue by bcomnes** [netlify/netlify-identity-widget#100]
Gotrue redirects back to the endpoint url instead of `localhost` in devmode.  We should disable the oauth provider buttons in devmode until we can support them in gotrue.

cc @erquhart

**Comment by tech4him1** [comment]
This should be a fix for #86, right @bcomnes?

**Comment by bcomnes** [comment]
We are planning to add improved redirect support, which should actually fix that rather than just hiding the issue.

**Comment by tech4him1** [comment]
Should be closed by https://github.com/netlify/gotrue/pull/132.

**Comment by bcomnes** [comment]
Tested this today, behavior is still the same.  I will follow up with a plan of action.

**Comment by bcomnes** [comment]
I clarified this today:

> The problem is trying to use a web page at location `A` when identity is configured for a site at `B`. It rightfully, refuses to redirect back to a referrer on `A`.

This holds true for localhost as well, so the best inturum solution is to make this as clear as possible.  Adding this to https://github.com/netlify/netlify-identity-widget/issues/40 and triaging it for a sprint soon.
