### ISSUE TITLE
Testing option for email templates

### ISSUE THREAD

**Issue by hdoro** [netlify/netlify-identity-widget#110]
As it stands, the widget must show up both in the CMS admin page and in the homepage. In order to optimize my homepage I was looking into ways of moving the signup process to the admin page, and I figured I could use a Go function in my email signup template to replace "domain.com" with "domain.com/admin", like so:

```html
<a href="{{replace .ConfirmationURL 'domain.com/' 'domain.com/admin/'}}">Accept the invite!</a></p>
```

But even though I use this page as the template for the signup in the Netlify Identity dashboard, the emails always follow the plain, default email. I figured there's an error with the page somehow, but I have no means of testing it other than making guesses and pushing tiny commits to my repo every time to see if it works.

So for this use case and many others (such as email styling and all), the **suggestion is: adding a 'test template' option to the identity dashboard**. I'm sorry if this issue should be filed somewhere else, please direct me to it if you can 😄

**Comment by adamryvola** [comment]
I have same problem.
Standard {{ .ConfirmationURL }} redirects to domain.com, not to domain.com/admin.
If I use your version (with replace) it sends blank email.

(Template without replace works ok, except link to root.)

Do you have some news about this issue?

**Comment by runandrew** [comment]
I am having the same problem, has anyone found a fix for this?

**Comment by jlengstorf** [comment]
the part of this that's not Netlify CMS-specific is the inability to change the confirmation path. that's tracked in https://github.com/netlify/netlify-identity-widget/issues/171, so I'm closing this to consolidate tracking to that issue
