### ISSUE TITLE
Mobx errors when bundled with browserify

### ISSUE THREAD

**Issue by bcomnes** [netlify/netlify-identity-widget#115]
<img width="602" alt="screen shot 2018-01-25 at 6 57 58 pm" src="https://user-images.githubusercontent.com/166301/35423249-b5f0f97c-0201-11e8-987f-ec0869c3042b.png">

Not sure whats going on but I can get this error reliably when bundling with browserify.

**Comment by jlengstorf** [comment]
closing this because I don't think browserify is a target for us — we can revisit if this assumption turns out to be incorrect
