### ISSUE TITLE
Cannot confirm email

### ISSUE THREAD

**Issue by MaralS** [netlify/netlify-identity-widget#116]
Hello everyone,
I'm starting using Netlify Identify to provide a simple backend for my react apps for my clients.

However, when I receive the confirmation email, or the reset email, I cannot connect to the backend.
It's seems like it does not confirm anything.

https://upbeat-neumann-cd2720.netlify.com/ here is the test website. You can test yourself by creating an account on https://upbeat-neumann-cd2720.netlify.com/admin/. You'll receive a confirmation email but when you click on the link nothing happens

What's is the problem ?

**Comment by bcomnes** [comment]
The link in the email confirmation is to the root URL of your site (`https://upbeat-neumann-cd2720.netlify.com/`) which does not have the widget present on the page to handle the confirmation token, so nothing is handling the confirmation token when you click on the link in the email.

We have proper redirect support landing in our hosted gotrue instances any day now, which will redirect users back to the page that originated the login request, so this current situation should just work.

In the meantime, adding a the widget to your root page should allow for the current email links to work.

**Comment by MaralS** [comment]
@bcomnes Thanks for the explanation I'll try to add this module on my home page.

**Comment by bcomnes** [comment]
Let us know if you run into any problems.  Closing for now, but we can reopen or create new issues if you run into any other issues.  Redirect support is coming soon and we will have some announcements/blog/twitter posts about it when it launches.

**Comment by futuregerald** [comment]
Hi @braco && @MaralS . You can create your own custom e-mail templates. We pass some variables in that you can use to point the confirmation link e-mail to any page on your site. As long as the netlify-identity-widget is loaded on the page you send people, it will pull the token from the URL and confirm the user. You can read more about this in our docs: https://www.netlify.com/docs/identity/#identity-generated-emails
