### ISSUE TITLE
Not compatible with Chrome <45, Firefox <39, Safari <10, Edge 13

### ISSUE THREAD

**Issue by jayvdb** [netlify/netlify-identity-widget#127]
http://identity.netlify.com login boxes do not appear on my basic pre-installed browser that comes with FIRA OS on Android 5.1 Polytron 4G 501 (Zap 6 Posh).

The User Agent is

> Mozilla/5.0 (Linux; Android 5.1; POLYTRON_4G501 Build/LMY47D) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/39.0.0.0 Mobile Safari/537.36

http://www.tera-wurfl.com/explore/?action=wurfl_id&id=polytron_4g501_ver1

**Comment by jayvdb** [comment]
I've also confirmed a similar problem with "Mozilla/5.0 (Linux; Android 4.4.4; 2014817 Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.109 Mobile Safari/537.36"

Seems there is a minimum version of Chrome which is supported at the moment.

**Comment by jayvdb** [comment]
It looks like Chrome 45 is the lowest version which is working.

Thus, most Android 5.1 and lower ship with an unsupported browser.

Also Firefox 30 is almost certainly broken as well, but it is a bit harder to verify due to https://github.com/netlify/netlify-identity-widget/issues/129 .  On my site, ciptamedia.org, Firefox <39 is failing.

Safari 7-9 are also broken.  Safari 10 works ok.

Internet Explorer 11 & Microsoft Edge 13 are broken.  Edge 14 works ok.

**Comment by jayvdb** [comment]
We fixed this in our app by adding

https://cdn.polyfill.io/v2/polyfill.js?features=default,fetch

**Comment by bcomnes** [comment]
I've heard a few reports regarding environments that don't ship a fetch api.  I'm considering adding a polyfill or documenting how it can be added.

**Comment by jlengstorf** [comment]
a refactor of this repo is in discussion, and will likely include `@babel/preset-env` to automatically add polyfills. in the time since this issue was created, though, Fetch API support has become _far_ more widespread, so I'm going to close this particular issue https://caniuse.com/#feat=fetch
