### ISSUE TITLE
Support translations for strings in the dialog

### ISSUE THREAD

**Issue by jayvdb** [netlify/netlify-identity-widget#128]
The dialog has very basic strings, commonly found in most apps, and translations will mostly already exist in TM for most languages.

**Comment by gorille** [comment]
Indeed, there should be an option to translate the widget, otherwise this won't be usable in international environments.

**Comment by bcomnes** [comment]
Agreed we should support this.  Unfortunately the only current solution is custom implementations or forking.  Hopefully we can revisit this in 2019.

**Comment by ndalliard** [comment]
Any updates on this?

**Comment by erezrokah** [comment]
Fixed via https://github.com/netlify/netlify-identity-widget/pull/238
