### ISSUE TITLE
identity.netlify.com buttons not visible in Firefox 44

### ISSUE THREAD

**Issue by jayvdb** [netlify/netlify-identity-widget#129]
On http://identity.netlify.com the "Log in" & "Sign-up" buttons are not visible in Firefox 40-44.
They render in Firefox 45.

Internet Explorer 9 also has the same problem, and presumably earlier IE also suffer, but I cant be certain of that.

Chrome 26+ all render the buttons ok, but they dont work per https://github.com/netlify/netlify-identity-widget/issues/127

Also Safari 7+ & Edge 13+ render the buttons ok.  I havent found where the buttons work correctly for those browers.

**Comment by bcomnes** [comment]
We should establish a browser support range.  It's my understanding Firefox 44 is no longer a supported Mozilla release, so it's unlikely much energy will be available to support a widget release that will test back that far.

**Comment by jayvdb** [comment]
Definitely agree wrt clarity about what will be supported, and communicating that to potential Netlify implementers so they dont get bitten unexpectedly.

Not being supported by a vendor isnt a good reason to unsupport a browser, especially when it comes to mobile devices.  They need to move on, to improve the future web, and then it is over to us to build and use shims to support the owners of old devices who certainly dont keep using old devices by choice.  They would upgrade if the could.  They cant, because they are disadvantaged for some reason, and it is a bit rich for 'us' to cutting them off from internet services because 'we' dont want to include an extra 100byte minified shim that is now effectively perfect because it has been around for 5 years.   Discussion about this is more relevant to https://github.com/netlify/netlify-identity-widget/issues/127 , which is the blunter edge of the support matrix problem of Netlify Identity as-is. (the buttons not rendering only effects people using the default buttons, which is quite easily worked around by an implementer.)

A more useful driver for completely unsupporting users is 'difficulty of testing', and due to testing VM's SaaS it is now typically easy and cheap to be able to test on prehistoric browsers, but even they have limits, and which verifying patches is no longer easy and it is reasonable to conclude that any Netlify implementer wanting to support users on those devices are on their own.

Back closer to the topic of this issue, Edge <13 looks like the most problematic breakage of the button rendering on the website at the moment, but a quick poke around the Netlify analytics should reveal which browsers are most commonly used and are currently seeing a badly rendered page at identity.netlify.com .
