### ISSUE TITLE
Identity widget with gotrue api?

### ISSUE THREAD

**Issue by ef0da37ba4** [netlify/netlify-identity-widget#130]
I'm trying to make the identity widget work with an instance of the GoTrue API (https://github.com/netlify/gotrue).  I'm currently using: 

```
<!DOCTYPE html>
<html>
<head>
  <title>A static website</title>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script type="text/javascript" src="/njs/netlify-identity-widget.js"></script>

  <script>
        jQuery(function() {
                netlifyIdentity.init({
                        APIUrl: "https://api.example.com",
                });

        });
  </script>
</head>
<body>
  <div data-netlify-identity-menu></div>
</body>
</html>
```

This works on the settings / signup calls but when I try and verify a newly created users confirmation token example.com/#confirmation_token=<token> it's calling example.com/.netlify/identity/settings instead of the `APIUrl` value.  My sense of it is `netlifyIdentity.init()` is being called twice and I need to use another function but I didn't see one when I looked.  Also passing `container` to init appears to do nothing.  Thank you!

**Comment by bcomnes** [comment]
The identity widget embeds its own instance of gotrue, so you should only use one or the other at the moment.

**Comment by bcomnes** [comment]
You can interact with the embedded gotrue instance on the widget though.

**Comment by ef0da37ba4** [comment]
@bcomnes Thank you Bret!  Maybe I'm confused but I did see GoTrue-JS was embedded but what I'm trying to get to is to use my own instance of the GoTrue API (https://github.com/netlify/gotrue) with the Identity Widget.  So it looks like from the docs I can just specify a new endpoint via `APIUrl` of the `netlifyIdentity.init()` but that doesn't appear to work (or I'm not understanding).  If I get access to the underlying GoTrue-JS how do I prevent `init()` from being called automatically in the identity widget?  If I'm understanding correctly I could roll my own identity widget using GoTrue-JS but if it's possible I'd like to just point the current identity widget at my GoTrue (API) instance.

**Comment by ef0da37ba4** [comment]
For others this can be done with something like this (NGINX):

        upstream go_app {
                server 127.0.0.1:9090;
        }

        location /.netlify/identity {
                proxy_redirect   off;
                proxy_set_header Host              $http_host;
                proxy_set_header X-Real-IP         $remote_addr;
                proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;

                proxy_pass http://go_app;
        }

**Comment by bcomnes** [comment]
I may use that in an example doc, thank you!  Closing for now.  Please reopen a new issue of things remain.

**Comment by cameronelliott** [comment]
For Caddy v2 users, this config did the trick, since I don't use nginx as much:

```
192.168.86.4:80

# Set this path to your site's directory.
#root * site

# Enable the static file server.
file_server

route /.netlify/identity/* {
	uri strip_prefix /.netlify/identity
	reverse_proxy localhost:9999
}
```


You can fix the IP address to your needs, and fix/remove ```root, file_server``` options as you need.
