### ISSUE TITLE
Local development inconsistent results

### ISSUE THREAD

**Issue by rwboyer** [netlify/netlify-identity-widget#131]
I âm testing a few different sites using identity. Some with Netlify cms, some with lambda functions. All of them have identity instances set up. They all work fine when deployed on Netlify but I cannot seem to get any of them consistently working on a local development environment. It seems almost random.

I've tried clearing local storage, using guest browser windows, pretty much everything.

I get the pop-up asking for the deployed site url the identity instance is tied to. Log in works fine but depending on what day it is I get 401 errors, etc... 

I've searched everything and cannot seem to find "the recipe" to get consistent results using identity in a local development environment.

Any particular recipe I'm missing here? Even the "demo apps" strait out of the box behave the same way... inconsistently. Sometimes local works, mostly it doesnt'

**Comment by bcomnes** [comment]
It sounds like localstorage is pointing to the wrong identity endpoint, a common pitfall around how we handle the local dev settings. 

Try running `localStorage.clear()` when you run into trouble.  

I'm going to close this in favor of https://github.com/netlify/netlify-identity-widget/issues/131 but we want to improve this flow soon, and add ways to configure the endpoint somehow (perhaps using oAuth metatags or something or simply through the module API.)
