### ISSUE TITLE
Login event only called on initial page load (NetlifyCMS)

### ISSUE THREAD

**Issue by knpwrs** [netlify/netlify-identity-widget#137]
I wasn't sure whether to open this issue here or over at https://github.com/netlify/netlify-cms. I have code which resembles the following:

```js
import 'netlify-cms/dist/cms.css';
import 'netlify-cms';
import netlifyIdentity from 'netlify-identity-widget';

const clearToken = () => {
  global.localStorage.removeItem('netlifyIdentityToken');
};
const saveToken = (user) => {
  if (!user) {
    clearToken();
  } else {
    global.localStorage.setItem('netlifyIdentityToken', user.token.access_token);
  }
};

netlifyIdentity.on('init', saveToken);
netlifyIdentity.on('login', saveToken);
netlifyIdentity.on('logout', clearToken);

netlifyIdentity.init();
```

I have observed the following behavior:

1. When I load a page with a valid Identity session both `init` and `login` are fired with a user object.
1. When I login to netlify cms the `login` event is _not_ fired. When I refresh the page the events work as expected.
1. When I logout of netlify cms the `logout` event does _not_ fire. The token stays in local storage but I am presented with a login screen. I still have a login screen when I refresh the page, so I know the session is invalidated.

**Comment by galvarez421** [comment]
I am also experiencing the number 2 item in that after I login, I have to refresh the page to see the admin interface.

**Comment by jlengstorf** [comment]
I don't know if this is still happening, but if it is, I _think_ this issue should start on Netlify CMS
