### ISSUE TITLE
Example app requires a tweak

### ISSUE THREAD

**Issue by HemalR** [netlify/netlify-identity-widget#138]
(Please advise if I have misunderstood/overlooked something!).

I tried the example code here to no avail: https://github.com/netlify/netlify-identity-widget/blob/master/example/src/App.js

In order to get it to work, I needed to add this:

```
	componentDidMount() {
		netlifyIdentity.init();
	}
```

Which makes sense... 

Thanks for the awesome new features! Getting more and more swayed to using Netlify for everything  😄

**Comment by bcomnes** [comment]
You only want to initialize once, outside of the DOM that react is controlling, so we do it in the app entrypoint:

https://github.com/netlify/netlify-identity-widget/blob/master/example/src/index.js#L10

**Comment by HemalR** [comment]
Doh! Of course. Sorry about that and thanks for the quick response.

**Comment by bcomnes** [comment]
No problem!
