### ISSUE TITLE
Custom confirmation url for new user invite

### ISSUE THREAD

**Issue by runandrew** [netlify/netlify-identity-widget#139]
I am using Netlify/Netlify CMS with a React Static Site. To access the admin panel, the Netlify CMS site is located at domain.com/admin. When I invite new users, they are sent to my root domain domain.com#token, which does not present anything to make a password (I believe this is because I do not have the identity widget on that part of my site).

Is there a way to change the confirmation url to direct straight to domain.com/admin?

Thanks!

**Comment by futuregerald** [comment]
@runandrew the netlify-identity-widget doesn't actually have any effect on this, it's how the gotrue instance used in Netlify is configured. You can't change the confirmation link URL, but you can use gotrue-js to handle that code by writing a custom method, or just import the netlify-identity-widget on your home page.

**Comment by runandrew** [comment]
Thanks for the information @futuregerald! Yes, I ended up putting the widget on my home page and that worked.
