### ISSUE TITLE
Name field has email icon

### ISSUE THREAD

**Issue by DavidWells** [netlify/netlify-identity-widget#140]
⊂◉‿◉つ

Do we want to use a person icon here instead of email?

![image](https://user-images.githubusercontent.com/532272/40814934-075c3944-64f8-11e8-8da0-11e69b738f23.png)

Maybe something like dis https://thenounproject.com/search/?q=person&i=737678 ?

**Comment by DavidWells** [comment]
Is there a place I can find commonly used icons in netlify UI? 

I can PR this if someone points me to icon svg

**Comment by lunaceee** [comment]
You can find them under the [Netlify React UI repo](https://github.com/netlify/netlify-react-ui/tree/master/src/images) or via [Abstract](https://www.goabstract.com/?ref=thesketchapphub) if you have an account, but you'll need to add Netlify to your dashboard.

**Comment by DavidWells** [comment]
Cool fixed!
