### ISSUE TITLE
Why do I get a 404 error when downloading a file from Git Gateway?

### ISSUE THREAD

**Issue by rfgamaral** [netlify/netlify-identity-widget#144]
As you might have already seen from #142, I have this flow to authenticate the user and load an `.html` file from a private GitHub repository (using Netlify's Git Gateway) after the user successfully logged in:

```js
const loadPrivateContent = function(privateFileUrl) {
    console.debug('loadPrivateContent -> privateFileUrl', privateFileUrl);

    $private.load(privateFileUrl, (response, status, xhr) => {
        if (status === 'error') {
            console.error('loadPrivateContent -> complete()',
                status, xhr.status, xhr.statusText);
        } else {
            console.info('loadPrivateContent -> complete()',
                status, xhr.status, xhr.statusText);
        }
    });
};

const getPrivateContent = function(accessToken) {
    $.ajax('/.netlify/git/github/contents?ref=secret', {
        headers: {
            'Authorization': `Bearer ${accessToken}`
        }
    })
    .done(data => {
        console.info('getPrivateContent -> done()');
        loadPrivateContent(data.find(file => file.name === 'private.html').download_url);
    })
    .fail((xhr) => {
        console.error('getPrivateContent -> fail()', xhr.status, xhr.statusText);
    });
};

$window.on('load', function() {
    const currentUser = netlifyIdentity.currentUser();

    if (currentUser) {
        currentUser.jwt().then(accessToken => {
            getPrivateContent(accessToken);
        });
    } else {
        netlifyIdentity.on('login', user => {
            getPrivateContent(user.token.access_token);
            netlifyIdentity.close();
        });

        netlifyIdentity.open('login');
    }
});
```

As you can see, I ask the user to login if he hasn't done so before. If he has, I call `currentUser.jwt()` to refresh the token if necessary. In either case, I call `getPrivateContent()`, passing the most recent `access_token` I have access to.

Inside `getPrivateContent` I make an HTTP GET request to `/.netlify/git/github/contents?ref=secret` so that I can list all contents on this project's Git repository, I use the `ref=secret` to access the `secret` branch. I have the `.fail()` handler just in case and for debugging purposes, but so far it never occurred, the request is always successful and `.done()` is always invoked. `data` contains the list of all files in the Git repository for the `secret` branch, just as I expected it (this works because authentication was successful and the `access_token` is valid).

The problem comes next, when I call `loadPrivateContent` with the `download_url`of the file I'm looking for. Inside this function I use `$private.load` I use jQuery's `load` method (an HTTP GET request) to get the contents of the file and place them inside the `$private` element. More often that not this fails and I can't download the private contents.

This fails with 404 (sometimes I also get `xhr.status === 0`) but the file is there. And what's more weird is that I have the code above deployed and testing both on my Android phone and my desktop. On the desktop I get a 200 OK, everything is fine, everything works. On the phone, I get the 404 Not Found. Why?

What am I missing? Why is this failing so often on mobile? I've used Chrome for Android and I've also tested this on an iPhone with both Chrome and Safari, it fails with the same error. But it works every time on the desktop.

Anyway, I'm fully authenticated, the toke is valid and the request to `/.netlify/git/github/contents?ref=secret` works just fine, there's no reason that the HTTP GET for the `download_url` shouldn't work either (especially just on mobile), or is there? It seems like the `token` appended to the `download_url` expires and the request fails, but since the request to `/.netlify/git/github/contents?ref=secret` returns successfully, the data from that request should contain `download_url`'s with valid tokens appended, right?

**Comment by imorente** [comment]
Sounds more like an issue related to the GitHub API than to Identity or Git Gateway themselves, but now I'm really curious to know why fetching the `download_url` fails on mobile!

As an alternative, have you tried reading the file contents straight from the GitHub API endpoint passing an "Accept" header? That'd also avoid having to make 2 separate AJAX requests.

```
const getPrivateContent = function(accessToken) {
    $.ajax('/.netlify/git/github/contents/private.html?ref=secret', {
        headers: {
            'Authorization': `Bearer ${accessToken}`,
            'Accept': 'application/vnd.github.VERSION.raw''
        }
    }).done(function(text) {
           // do stuff with the html content
    });
```

**Comment by rfgamaral** [comment]
> but now I'm really curious to know why fetching the `download_url` fails on mobile!

The only thing I can think of (but haven't yet tried) is that maybe mobile browsers are caching the `download_url` request and returning old contents (with an invalid `token` appended to the `download_url`).

On my way to work I was also thinking about this and the only thing that I could think of was "maybe the request is being cached". Since I'm using jQuery, there's a `cache: false` that I can use; it works by appending "_={timestamp}" to the GET parameters. Just tried this and I guess I was right, the `download_url` now contains a different `token` parameter every time I refresh the page and nothing fails anymore.

But your solution is better, spares me one additional request and looks like I may not need the `cache: false` option. I'll need to test this more thoroughly though, but if it happens again, browser caching is probably the issue.

**Comment by rfgamaral** [comment]
@imorente Thank you so much for your help, everything seems to be working as expected. Closing this now :)
