### ISSUE TITLE
Local lambda can't access clientContext

### ISSUE THREAD

**Issue by oliverjam** [netlify/netlify-identity-widget#149]
Not sure if this is the right repo for this, but I can't see an obvious one for Netlify Functions.

I can't seem to get a locally running Function to access a logged in user's `clientContext`. It works fine on the deployed site with code copied from the [Slack tutorial example](https://github.com/biilmann/testing-slack-tutorial/blob/v2-only-logged-in-users/src/App.js). I'm sending the bearer token in the header, which is definitely being picked up by the Function fine. `context.clientContext` is always undefined locally, but the correct user context on the deployed site.

Is this a known limitation of the Identity/Functions integration? It makes developing any authenticated functions pretty difficult as you have to deploy to see anything work.

**Comment by Mottokrosh** [comment]
I believe this is a current limitation with social logins. I ran into the same problem. If you register an account with username/password instead you should see the populated `clientContext`. As you say, it does work in production however.

**Comment by oliverjam** [comment]
I wasn't using an OAuth login here; it was a username/password. OAuth definitely doesn't work because the provider redirects to the production domain rather than localhost.

I think this may be an issue with the netlify-lamdba package, as this appears to be the same problem: https://github.com/netlify/netlify-lambda/issues/51

**Comment by rodocite** [comment]
I'm running into the same problem. There is a clientContext object when native Identity functions are fired. But the context is empty when you do a fetch request against the lambda like in this example for `functions/create-manage-link.js`:

https://www.netlify.com/blog/2020/07/13/manage-subscriptions-and-protect-content-with-stripe

There may possibly be an extra step needed so Netlify will provide the lambda w/ Identity context. Then using that context, do whatever identity-bound process that needs to be done.

**Comment by erezrokah** [comment]
Thanks for bumping this @rodocite. This seems more of a Netlify CLI issue than an Identity issue.
The CLI should populate the context argument with information from the authorization header:
https://github.com/netlify/cli/blob/51925e4fc6d5f6ce24c33df24a118480d69e536f/src/utils/serve-functions.js#L75

If that is not the case, can you please [open an issue](https://github.com/netlify/cli/issues/new) on the CLI repo.
It will help us get an up to date reproduction.

Closing this in favour of a possible new issue under the CLI repo.
