### ISSUE TITLE
Consider using zouhir/preact-habitat

### ISSUE THREAD

**Issue by bcomnes** [netlify/netlify-identity-widget#158]
Since our integration as a widget has been painful, perhaps we can port over the widget to use https://github.com/zouhir/preact-habitat instead and delegate the widget details to that framework.  

I haven't used it, but not dealing with widget defensiveness sounds awesome.

**Comment by sw-yx** [comment]
what is the painfulness you are referencing?

**Comment by bcomnes** [comment]
Just having to maintain our own iframe rendering system, mounting/lifecycle confusion, and issues with autofill.  I can't guarantee either of these issues would be solved by switching, but if they are I think we should consider it.
