### ISSUE TITLE
Would there be a way to customize the widget to show a role field?

### ISSUE THREAD

**Issue by q-omar** [netlify/netlify-identity-widget#162]
You can set roles manually through netlify dashboard but would there be a way to have a role selection inside the widget?

**Comment by sw-yx** [comment]
possible. need to get the data from gotruejs and reveal it in the UI. however i dont expect this to be a common use case and if you need that kind of power i suggest dropping down one level to gotrue-js itself.

**Comment by rcaracaus** [comment]
Here is an demo example of how to add a custom field meta data https://github.com/rcaracaus/netlify-identity-widget/commit/e32c92cdcd14396f05cd8fc3c67b62ce128ff616

Unfortunately, you have to fork the widget to do this at this point.

**Comment by sw-yx** [comment]
you want to PR something in? honestly forking is not such a bad thing to make the UI you want.

**Comment by rcaracaus** [comment]
I don't think a PR is necessary... we are probably just going to fork it. I just put the example up for reference.

**Comment by sw-yx** [comment]
cool :) thanks!
