### ISSUE TITLE
Feature Request: Ability to gate signup on agreement with Terms of Service (TOS) and Privacy Policy

### ISSUE THREAD

**Issue by renschler** [netlify/netlify-identity-widget#163]
Use Case: I want new users to be forced to review & agree to my app's terms of service before they can create an account. Currently I have them review the terms after signup, but this is a suboptimal flow bc by then I've already captured some of their information (their name and email address) and it add's another page to the getting started process.

If we could pass a 1 liner to the netlify widget, something like "By signing up you have read and agreed to the terms of service and privacy policy" with links to the relevant documents, that would be incredibly helpful. Even better would be a checkbox next to that line, which new users have to click before they can create an account.

Update: Just adding more details on where this request came from. I'm not a legal expert but I think now (more than before) with GDPR many netlify users are going to want/need a TOS gate, and having it post-signup means you've taken on more legal risk/complexity because by then you've already stored customer information without their explicit consent.

**Comment by sw-yx** [comment]
happy to take a PR for this but for what its worth there will always be some level of customization we cant support (not super well defined right now). If you want fuller control there is always https://github.com/netlify/netlify-auth-providers and https://github.com/netlify/gotrue-js and you can also roll your own with Netlify Functions.

**Comment by michalhudecek** [comment]
This would be great to have. It is basically required by law in EU to have these checkboxes in sign up forms so any sign up form without it is unusable.

**Comment by skllpr** [comment]
So something that you could look into is verification emails (through netlify) that have the required details (and click here to state you read the above content etc). Not sure if this satisfies the EU policy though.
