### ISSUE TITLE
Relink github to the canonical website.

### ISSUE THREAD

**Issue by bcomnes** [netlify/netlify-identity-widget#165]
It looks like somehow (probably during the github apps migration) this repo was linked to https://objective-bell-b86ce8.netlify.com/ owned by @sw-yx ?  Lets get it re-linked to https://app.netlify.com/sites/identity/deploys.

**Comment by sw-yx** [comment]
ummm i definitely didnt do that intentionally

**Comment by bcomnes** [comment]
Yeah looks that way, I wonder why the webhooks aren't getting sent to this one.  If you don't have time to look into it, just unassign and someone can look into it later.

**Comment by jlengstorf** [comment]
I sure hope this one was solved already 😂
