### ISSUE TITLE
I have built an example in Vue.js and submitted a pull request 

### ISSUE THREAD

**Issue by medmin** [netlify/netlify-identity-widget#168]
I have created a new branch "example-vue" but your repo does not have it yet. And I have pushed to master branch.

Let me know if I have done it right. Thanks

Regards,

Yumin

https://github.com/whizjs/netlify-identity-demo-vue

**Comment by shortdiv** [comment]
Closing, since this has been merged: https://github.com/netlify/netlify-identity-widget/pull/167.
