### ISSUE TITLE
netlifyAuth.isAuthenticated returns false on reload

### ISSUE THREAD

**Issue by goras** [netlify/netlify-identity-widget#172]
More specifically, I can login and stay logged in as long as I only navigate on the client. If I reload the page, the `netlifyAuth.isAuthenticated` always return false. If I click the login-button after the page has been reloaded, I get the popup saying I'm already logged in. 

Since I've found no issues regarding this, I assume I'm missing something obvious, but for now I'm just stuck so I'd be very thankful for some help!

The values set in localStorage are:
````
netlifySiteURL = https://my-app.netlify.com
gotrue.user = {
	"url": "https://my-app.netlify.com/.netlify/identity",
	"token": {
		"access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9......",
		"token_type": "bearer",
		"expires_in": 3600,
		"refresh_token": "UCzVpT9SnfS7....",
		"expires_at": 1548244499000
	},
	"id": "fe5894a4-0f26-41e4-9ceb-bdd12...",
	"aud": "",
	"role": "",
	"email": "name@gmail.com",
	"confirmed_at": "2019-01-22T19:36:43Z",
	"confirmation_sent_at": "2019-01-22T19:36:26Z",
	"app_metadata": {
		"provider": "email",
		"roles": ["Super"]
	},
	"user_metadata": {
		"full_name": "first last"
	},
	"created_at": "2019-01-22T19:36:26Z",
	"updated_at": "2019-01-22T19:36:26Z"
}
````

**Comment by sw-yx** [comment]
the react example is indeed written this way: https://github.com/netlify/netlify-identity-widget/blob/4edc7fca07cc242b24c2fd3a42fde97f91b6a38d/example/react/src/App.js#L42

to fix this, read localstorage on mount or on load. you comfortable modifying the code to do that?

**Comment by goras** [comment]
Ah thanks for the quick reply! Now it's working as expected!

**Comment by sw-yx** [comment]
cool
