### ISSUE TITLE
Is it possible to create a one time signed urls?

### ISSUE THREAD

**Issue by joegeneral** [netlify/netlify-identity-widget#179]
I need to create a one time use signed url so I could provide an external link to gated content, but the receiver would have to be signed up on my site, otherwise they would be redirected to a sign up page.  Is this something I can do with the identity widget?

**Comment by jlengstorf** [comment]
you could do this with Netlify Functions and Netlify Identity, but I don't think the widget will come into play for this workflow

it's not quite what you're after, but for an example of managing users with Identity + Functions, I wrote a [tutorial that handles validating users and roles](https://www.netlify.com/blog/2020/07/13/manage-subscriptions-and-protect-content-with-stripe/?utm_source=github&utm_medium=stripe-subs-jl&utm_campaign=devex)
