### ISSUE TITLE
Confirmation not working with widget

### ISSUE THREAD

**Issue by cfjedimaster** [netlify/netlify-identity-widget#182]
I am *very* new to Identify and the widget so this is most likely my fault. It may also be a Netlfiy issue and not the Widget.

I set up a very simple instance of the widget at https://identifydemo1.netlify.com/private/.

My code is just:

```
<html>
<head>
	<script src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
</head>
<body>
<p>
	Login
</p>


  <div data-netlify-identity-button>Login with Netlify Identity</div>
  
</body>
</html>
```

With this redirect setup:

```
/private/*	200!	Role=admin
/private/*	/login.html	401!
```

When I access https://identifydemo1.netlify.com/private/ I get redirected to my login page, I can click to load the widget, and then I can sign up as a new user. In my last test I used raymondcamden+user1@gmail.com.

I got the confirmation email, clicked the link, and back in the widget when I tried to login I was told I wasn't confirmed yet.

I'm guessing the issue is something missing at the confirmation step. When I click the link, I end up at https://identifydemo1.netlify.com/#confirmation_token=-NG3ZiNR7ovN_qztUMIlTQ, and as I have no code there to handle the confirmation, I'm guessing I'm missing something.

**Comment by futuregerald** [comment]
Hi @cfjedimaster, you need to have the widget on your home page to process that confirmation token. You can just add the script tag to your home page and that should take care of it.

**Comment by cfjedimaster** [comment]
testing now - thank you

**Comment by cfjedimaster** [comment]
confirmed - thank you!

**Comment by cfjedimaster** [comment]
Hey can I push my luck and ask a related question? (I'll do so. ;)

Given the redirects you see above, and given I'm using the widget on /private/index.html (this is a super simple test of mine, not a SPA, just 3 HTML files): When I hit /private, I get redirected to /login.html. I click the widget and it stays I'm logged in. So the server side redirect is not noticing that I'm logged in.

Does that make sense?

**Comment by futuregerald** [comment]
The server side redirect is never aware of your login state. The redirect works by verifying the signature of the JWT and checking the role in it to see if it matches the redirect rule.

**Comment by futuregerald** [comment]
If the redirect isn't working properly then I recommend opening a ticket with Netlify so we can help you debug :)

**Comment by cfjedimaster** [comment]
Yeah I was a bit unsure of how the login widget was 'marking' the browser, I thought maybe w/ a cookie that would be picked up server side. 

My intent was a vanilla HTML site (not SPA) with login/redirect as just a simple test. So you are saying that would *not* be supported, right? (Which is fine I guess, I'm learning this.)

**Comment by futuregerald** [comment]
That is suppoted. We save the jwt in a cookie named nf_jwt and verify that jwt on the edge for redirects. It works really well with static sites, and we use it for many of our internal sites that don't use SPA's.

**Comment by cfjedimaster** [comment]
Sorry if dumb - but what repo is appropriate for "netlify as a whole" ?

**Comment by cfjedimaster** [comment]
Dumb question - what repo? I'm on the main Netlify org at GitHub and don't seem to see one for "the platform" (if that makes sense).
