### ISSUE TITLE
Netlify Identity open hidden pages

### ISSUE THREAD

**Issue by Wallvon** [netlify/netlify-identity-widget#187]
I want to make that if someone logs in to my site with the Netlify Identity widget that that person can view a webpage that people that are not logged in cannot see. How can I do this? (Sorry for my bad English)

**Comment by shortdiv** [comment]
Hi,

Thanks for the question! There are a couple of ways to ensure gated content is only accessible to logged in users.  One is to check for a user's role in a Netlify function and the other is to use role based access control. 

The first option requires checking for the user's credentials either in `context.clientContext` or in the event body if you prefer explicitly passing the user when you make that function call. So something like this: 

```
```

Both require setting the user's role when a new user signs up. To see an example of how this is done, check this example out: 
Demo: https://login-to-gated-site.netlify.com/
Repo: https://github.com/shortdiv/jwt-generate

As for the first option

**Comment by shortdiv** [comment]
Hi,

Thanks for the question! There are a couple of ways to ensure gated content is only accessible to logged in users.  One is to check for a user's role in a Netlify function and the other is to use role based access control. 

The first option requires checking for the user's credentials in `context.clientContext`. So something like this: 

```
export function(event, context, callback) {
  const { identity, user } = context.clientContext;
  if (user.app_metadata.roles != 'visitor') {
    // Call a secret function to hydrate your application with secret data only logged in users can see
    return callback(null, {
      statusCode: 200,
      body: JSON.stringify({ message: "hello there, this is some super secret data" })
    });
  } else {
    //data is secret//
    return callback(null, {
      statusCode: 200,
      body: JSON.stringify({ message: "hello there, sorry but this data is secret and requires log in" })
    });
  }
}
```

The second option is as easy as setting a role based redirect rule in the redirects file. This option however requires a Teams Business plan or above. To do a redirect this way, you add this rule to your `_redirects` file: 

```
/admin/*	200!	Role=admin
```

Both require setting the user's role when a new user signs up. By default identity does not set a user's role. You will have implement this yourself. To see an example of how this can be done, check this demo out: 
Live demo: https://login-to-gated-site.netlify.com/
CodeRepo: https://github.com/shortdiv/jwt-generate
