### ISSUE TITLE
Add ability to logout when roles are not accepted

### ISSUE THREAD

**Issue by lewnelson** [netlify/netlify-identity-widget#192]
# Issue

When a users roles are not accepted after they have logged in/signed up they remain on the login page. If a users roles are updated via the Netlify identity dashboard the changes are not reflected for the user until they refresh their token.

The token however is stored in `localstorage` with the only method of deletion through manually deleting the token and logging in again.

# Steps to reproduce

1. Restrict access to the CMS with roles.
1. Create/signup/invite a user with no roles.
1. Attempt to login as that new user.
1. You will receive an error saying you do not have sufficient permissions to access the CMS.
1. Change that new users roles within the identity section of the Netlify dashboard to allow them access.
1. Go back to the CMS and login as that user again (you are already logged in with no way of logging out, you have to bypass localstorage at this point as the current token does not contain the roles required).

# Workaround

I've hacked together some JavaScript which will allow the user to manually logout if they are experiencing this issue. Ideally there would be a logout button integrated into the identity widget.

```
// Clears token generated on login to prevent manual deletion to update roles
(function() {
  var interval
  var showingLogoutButton = false;
  function getLoginButton () {
    var buttons = [];
    var buttonElements = document.getElementsByTagName('button');
    for (var i = 0; i < buttonElements.length; i++) {
      buttons.push(buttonElements[i]);
    }
    return buttons.filter(function (button) {
      return button.innerText.match(/^login\swith\snetlify\sidentity$/i) !== null
    }).shift();
  }

  function isLoggedIn () {
    return !!window.localStorage['gotrue.user'];
  }

  function logout () {
    delete window.localStorage['gotrue.user'];
    hideLogoutButton();
    window.location.reload();
  }

  function showLogoutButton () {
    if (!isLoggedIn()) return;
    if (showingLogoutButton) return;
    var loginButton = getLoginButton();
    if (!loginButton) return;
    var logoutButton = document.createElement('button');
    logoutButton.setAttribute('id', '--logout-buton')
    loginButton.classList.forEach(function (className) {
      logoutButton.classList.add(className);
    });
    var logoutText = document.createTextNode('Logout, if you are experiencing issues retry logging in');
    logoutButton.appendChild(logoutText);
    loginButton.parentElement.insertBefore(logoutButton, loginButton.nextSibling);
    loginButton.style.display = 'none';
    logoutButton.addEventListener('click', logout);
    clearInterval(interval);
    showingLogoutButton = true;
  }

  function hideLogoutButton () {
    if (!showingLogoutButton) return;
    var loginButton = getLoginButton();
    if (!loginButton) return;
    var logoutButton = document.getElementById('--logout-buton');
    logoutButton.removeEventListener('click', logout);
    logoutButton.parentElement.removeChild(logoutButton);
    loginButton.style.display = 'block';
    showingLogoutButton = false;
    runInterval();
  }

  function runInterval () {
    interval = setInterval(showLogoutButton, 500);
  }

  runInterval();
})();
```

How the workaround looks in action
![netlify_login](https://user-images.githubusercontent.com/11139198/58966149-a6d96a80-87a9-11e9-9b6b-ceedce9ee2fa.gif)

**Comment by jlengstorf** [comment]
this appears to be an issue for Netlify CMS. I also realize that this is a very late reply, so if this is still an issue for you, could you please open this issue on the [Netlify CMS repo](https://github.com/netlify/netlify-cms)?
