### ISSUE TITLE
[doc] Development, localhost, init

### ISSUE THREAD

**Issue by narvik-tribe** [netlify/netlify-identity-widget#194]
I suggest to add a line to the Localhost section in the Readme, that reminds to call
```
netlifyIdentity.init()
``` 
with no parameters when developing on localhost, to trigger the request for the site URL for dev mode

Otherwise, using the APIUrl parameter, the page is redirected to the wrong place, or doesn't work at all if the parameter is set to http://localhost

**Comment by jlengstorf** [comment]
this should no longer be an issue — please open a new issue (a reproduction or screen recording of the problem would be _very much_ appreciated!) if localhost is causing problems!
