### ISSUE TITLE
Use a custom local domain : mydomain.local

### ISSUE THREAD

**Issue by GuilhemBarboux** [netlify/netlify-identity-widget#196]
Hi,

i use the widget on local with a custom domain name : mydomain.local
I see a list of localhost domaine name : 
`const localHosts = {
  localhost: true,
  "127.0.0.1": true,
  "0.0.0.0": true
};`
Do you know a way to make it work, or maybe i can create a PR with a solution based on :
`windows.netlifyIdentifyConfig = {
  localhost: 'mydomain.local'
}`

What do you think ?

**Comment by sw-yx** [comment]
havent tried this before, sorry. try asking https://community.netlify.com/
