### ISSUE TITLE
Cannot test in localhost because widget automatically redirects to my netlify URL

### ISSUE THREAD

**Issue by vibrunazo** [netlify/netlify-identity-widget#197]
When I run my website on localhost, the Idendity Widget automatically redirects me to my website URL if I try to log in using Google External login.

Steps to reproduce:
1) run my website at localhost:4200
2) open Idendity Widget modal dialog
3) type in my netlify url, as instructed in the Widget readme 
4) Widget correctly loads my settings from ./netlify/idendity and shows me the Google login I had configured
5) Click on the button to login with Google on the modal
6) The widget now redirects me to my website url, outside of localhost. The deployed website in my url naturally still doesn't have the changes I made in localhost. So I cannot test those changes.

Expected outcome:
6) The widget should not redirect away from localhost after login. So I can test the changes I made to localhost and see how they look like after login.

If I deploy my changes to a development branch, then everything is working 100% fine. But I have to deploy to that branch every time I make a change related to idendity login. Because I cannot see those changes in localhost.

**Comment by sw-yx** [comment]
i think this is as designed. i know its annoying but we state very clearly that external providers like google are not supported on localhost. i think this is controlled on the netlify identity/gotrue side of things so we cannot change it from the netlify identity widget perspective. sorry.
