### ISSUE TITLE
Sapper implementation creating multiple iframe tags

### ISSUE THREAD

**Issue by Chris56974** [netlify/netlify-identity-widget#198]
I'm not sure if this is an issue with Sapper or with the way things are setup (I'm a newer dev). But when using this [repository](https://github.com/spiffytech/sapper-netlify-cms-starter) (not mine). Every time you ...

1. Click off the home page onto another page
2. Click back onto the home page

Another iframe tag is created for the netlify-identity-widget. This can continue infinitely, creating mobx warnings in the console, etc. 

![image](https://user-images.githubusercontent.com/45607257/64925004-e13ea480-d7a7-11e9-88bd-fdfc1ddfadf2.png)

**Comment by sw-yx** [comment]
it's probably them. file an issue there and try removing this line https://github.com/spiffytech/sapper-netlify-cms-starter/blob/59edddc8b7e7cbc30a21f609e8e6720dbfac1043/src/routes/index.svelte

**Comment by Chris56974** [comment]
Thank you very much sw-yx ! 

I removed line 53 (which is what I assumed you meant) and it's working perfectly. I was trying to follow the [Netlify CMS docs](https://www.netlifycms.org/docs/add-to-your-site/#add-the-netlify-identity-widget), and they mentioned adding the script in the `<head>`, but perhaps this is not necessary for Sapper projects 🤔 ?

Much appreciated

**Comment by sw-yx** [comment]
as someone who is newer, be prepared to run into a lot of unclear bugs especially when you're messing with newer tech like svelte and sapper. you're still welcome to do it tho
