### ISSUE TITLE
Demo example in Svelte

### ISSUE THREAD

**Issue by babycourageous** [netlify/netlify-identity-widget#217]
Hi there

If you are looking to add another example to the examples folder, I whipped up one in Svelte. 

Based on the addition of the Vue example I didn't submit a pull request cause it sounds like adding folder happens on your end of things? If you decide to throw it in the mix I welcome any feedback (also let me know if pull request is the way to go)!

https://github.com/babycourageous/netlify-identity-demo-svelte

**Comment by sw-yx** [comment]
i dont even remember the vue example lol

honestly, we dont need it in here. you can just PR a link to your repo in the README?

**Comment by babycourageous** [comment]
Can do - if you like I can add your React demo and that Vue one as links as well?

**Comment by sdras** [comment]
The Vue one is a folder with a readme in it with a link, would be good to keep it consistent. You can create the folder for Svelte in the PR. @sw-yx feel free to sound off if you see any reason not to keep the convention we already have.

**Comment by babycourageous** [comment]
Thanks @sdras. I'll start there and check back tomorrow if that OG convention isn't preferred.

**Comment by sw-yx** [comment]
sure sure. i dont have strong feelings on it

**Comment by sdras** [comment]
Thank you for the PR! 🎉

**Comment by babycourageous** [comment]
You bet!

**Comment by QuantumInformation** [comment]
The live demo links to the vue one

**Comment by babycourageous** [comment]
Whoops... Just corrected that overlooked link. 
Thanks @QuantumInformation!
