### ISSUE TITLE
Question: Can one return a custom error message when name field validation fails?

### ISSUE THREAD

**Issue by PaulKElliott** [netlify/netlify-identity-widget#219]
I'ed like to check the uniqueness of the name field in my DB in the identity-validate or identity-signup functions.  If no bueno, return a custom message: "Name already taken."   Almost same-same as the email field, so I expect its already possible, just did not turn up any docs on it...

**Comment by sw-yx** [comment]
you'll need to go lower level than this library i think. use gotrue-js's get user api https://github.com/netlify/gotrue-js#user-content-get-a-user

theres also an endpoint for listing users in case you need that.

if you find an easy way to expose it on this netlify identity widget, i'm happy to consider a PR.
