### ISSUE TITLE
Question: Best way to distinguish between new and returning users?

### ISSUE THREAD

**Issue by jackbridger** [netlify/netlify-identity-widget#220]
Hi, thanks for developing such a great tool.

I would like to create an onboarding experience for new users only so I would like to distinguish between users who signed up and users who logged in. 

I understand there is not a 'signup' event, is there an equivalent workaround? If so I'd be happy to add something to documentation. 

Thanks!

**Comment by jackbridger** [comment]
As an update, it is possible with lambda functions: https://docs.netlify.com/functions/trigger-on-events/#available-triggers

**Comment by jlengstorf** [comment]
@jackbridger thanks for posting what you found!
