### ISSUE TITLE
Verify user server side

### ISSUE THREAD

**Issue by abtx** [netlify/netlify-identity-widget#222]
Hi. I'm trying to verify my user's permissions server side. My user authenticates using Netlify Identity. When the user updates something in their account, I want to verify if the request came from an actual user and whether they have the permission to so.

My idea is I use JWT verification with `nJwt.verify`, but it requires toke and secret. I've got the former with the gotrue user object, but not the former. Where can I get the secret from in Netlify?

If there is another recommended way to go about request validation, give me a shout. I'm trying to get my head around this but I'm new to this so any pointers are welcome. Thanks!

**Comment by marg51** [comment]
Hi there, I'm in the same boat.

It seems that you have to be a paid customer to access it.
It is located in your site settings, under Control Access

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/543507/72818679-29953400-3c6c-11ea-94a5-ae2d30efb4b4.png">

TBH, I'm not sure that's the same secret than the one used in Identity (why is it in a different section?)


related, although a bit old: https://www.netlify.com/blog/2018/01/23/getting-started-with-jwt-and-identity/

**Comment by jlengstorf** [comment]
if you're using Netlify Identity with Netlify Functions, the JWT will automatically be verified and added in the `context` argument. this repo shows how that can work if you're using Identity roles to protect content:

https://github.com/stripe-samples/netlify-stripe-subscriptions/blob/6e914a3b729362539ebc9ae100bfe6adcc9d11f9/functions/get-protected-content.js#L35-L39

if you need to access a third-party service, you could add a Netlify Function as a proxy to validate the user token and send the request from there, which removes the need to get the JWT secret

hope that helps!
