### ISSUE TITLE
Brute force prevention

### ISSUE THREAD

**Issue by frontcraft** [netlify/netlify-identity-widget#225]
**Problem description**

This issue relates to the "Log in" widget. An authentication request with wrong credentials at the login panel returns the message “No user found with this email”. An potential attacker could try to identify existing email addresses as login name, which then can then be used for brute-force attacks on the password. An attacker could try to identify valid credentials by trying out a huge number of possible passwords.

**Solution**

1. The message should only contain the fact that the login was not successful, not leaking further information about which data is incorrect.

2. The widget should be configured to block the originating IP-Address if too many login attempts have been detected.

**Comment by ecerroni** [comment]
I thought the same. No useful clues should be given to potential hackers.

**Comment by erezrokah** [comment]
This should be handled here https://github.com/netlify/gotrue/blob/49e0866b91fa6b28b098163765d513621c171c98/api/token.go#L62.

The identity widget is a client side widget, so having these kind of mechanisms in the widget won't have security benefits (maybe other benefits of client side validation).

**Comment by lloydjatkinson** [comment]
This has now been fixed in the linked PR.
