### ISSUE TITLE
Login Page is Not Responsive

### ISSUE THREAD

**Issue by jaider** [netlify/netlify-identity-widget#230]
How to reproduce:
- Deploy a Netlify CMS website
- Go to Admin Page and try to login in your smart-phone

Expected: 
The page to be responsive.

Actual:
The page is not responsive. 

![image](https://user-images.githubusercontent.com/34106843/74591661-97641f80-4fce-11ea-9727-4b1c687d2e4a.png)

![image](https://user-images.githubusercontent.com/34106843/74591602-0db45200-4fce-11ea-83d4-9c25c4ed2005.png)

**Comment by jlengstorf** [comment]
hey there! this widget is responsive (see attached screenshot), so I think this may be a Netlify CMS issue? https://github.com/netlify/netlify-cms

![Screenshot_20200729-155123](https://user-images.githubusercontent.com/163561/88861826-a8d36980-d1b3-11ea-87fb-086a2492dc1e.png)


I realize I'm replying to this pretty late, so this may already have been handled, but in case you're still hitting it, would you mind opening an issue on the [Netlify CMS repo](https://github.com/netlify/netlify-cms)? thank you!
