### ISSUE TITLE
Question: how to use refresh tokens

### ISSUE THREAD

**Issue by ricokahler** [netlify/netlify-identity-widget#234]
Hi there,

Thanks for this great tool! I just have one question on how to implement refresh tokens. I've tried manually calling the `token` endpoint and writing the results to localStorage but that doesn't seem to work. I'm guessing there's some sort of internal state I need to update besides localStorage in the widget after I refresh the token.

Is there anyway to do this?

Thanks again!

**Comment by carlganz** [comment]
I believe this is related to this issue: https://github.com/netlify/gotrue-js/issues/71

Currently refresh tokens don't seem to work. I don't really understand how the "remember me" functionality is implemented in the widget (I'm guessing it doesn't work) or how to actually refresh a stale token.

**Comment by jlengstorf** [comment]
this is a late reply, but this _does_ work now!

for a working example, check out this repo that forces a JWT refresh to ensure roles are up-to-date:
https://github.com/stripe-samples/netlify-stripe-subscriptions/blob/main/src/index.html#L147
