### ISSUE TITLE
oAuth redirect issue

### ISSUE THREAD

**Issue by abtx** [netlify/netlify-identity-widget#235]
I’ve struggled for some time to get identity work with React and I still come across issues. 

I assume that these should be true:

`1 - widget connects to whatever APIs needs, and redirects
2 - user is available in netlifyIdentity after the redirect is complete using netlifyIdentity.currentUser()`

This flow is true on Safari;

On Chrome and FF, I get this behaviour:

`1 - widget connects to whatever APIs needs, and redirects
2 - netlifyIdentity.currentUser() returns null`

For reference:

deployment https://romantic-davinci-c26b02.netlify.com/login
repo: https://github.com/abtx/identity-widget

Please help me understand why the code works differently between browsers and what’s the correct implementation.

**Comment by jlengstorf** [comment]
this is a late reply, and it looks like you already solved this in your repo, @abtx, but I wanted to follow up for future Googlers

listening for the `init` and/or `login` event will avoid a null user object:

```js
netlifyIdentity.on('init', (user) => {
  // do something with the user
});
```

I hope this helps!
