### ISSUE TITLE
mobile usability of dismiss modal after successful log in

### ISSUE THREAD

**Issue by harlanlewis** [netlify/netlify-identity-widget#236]
Issue:
After logging in, the modal does not have a visible target to dismiss it and continue using the site.

Device:
Using iPhone 7, Safari. I imagine this issue also affects other devices with similar viewports.

Steps:
1. Inside the Log In modal (which covers the viewport on mobile as a faux page),
2. when a user puts focus on a form field (email, password),
3. the viewport zooms in slightly for the input to fill the screen width and scrolls to position it above the keyboard.
4. After submitting the log in form successfully, the modal remains zoomed in.

Because the 'close' button is positioned horizontally outside of the zoomed-in form area, there is no visible way to dismiss the modal and return to the site. The zoom is subtle enough to be easily missed, making it appear that the site must be reloaded to continue.

![IMG_0724](https://user-images.githubusercontent.com/51766/80252947-3475b100-862d-11ea-9df1-5fb7f35d7db9.jpg)

**Comment by peterp** [comment]
I've also been thinking about this, the "LOGOUT" button is the thing that I want to tap on in this screen, even though it's the first thing I see directly after logging in.

![image](https://user-images.githubusercontent.com/44849/81818178-fd106b00-952d-11ea-873d-509ace20182a.png)

**Comment by peterp** [comment]
Maybe something like `netlifyClient.login({ loginSuccessModal: false })`

**Comment by cameronelliott** [comment]
I think this is an awesome contribution to the open source world by Netlify, and I really love the look of the widget, but to be honest, after my users login, the last thing I want them to do is be presented with a "Logout button", and have to figure out they need to hit the little "x" in the upper right corner of the widget in order to accomplish their task.
So, the widget is fantastic, but the UI flow could really use some more thought and work.

**Comment by joaobraq** [comment]
I have created hotfixes that solve the two problems described in this issue.

For the zoom in problem originally described by @harlanlewis, [it is known that iOS will only zoom in input elements if their font-size is below 16px](https://stackoverflow.com/a/6394497), therefore we can solve this by adding a bit of CSS to the iframe:

`netlifyIdentity.on('open', function() {
  var iframe = document.getElementById("netlify-identity-widget");
  if (iframe) {
    var iOSfix = iframe.contentWindow.document.createElement("style");
    iOSfix.innerText = "input { font-size: 16px!important }";
    iframe.contentWindow.document.body.appendChild(iOSfix);
  }
});`

The effect this has on the design is minimal and I wonder if the community/maintainers would be open to officially changing the font-size to 16px:

<img width="472" alt="16px" src="https://user-images.githubusercontent.com/24698114/88431558-fecd9900-cdd0-11ea-9960-48d76d8a8aa1.png">

As for the quality of life improvement suggested by @peterp of auto-closing the modal on login, we can use a similar technique of accessing the DOM of the iframe to auto-click the close button:

`function closeIdentityModal() {
  var iframe = document.getElementById("netlify-identity-widget");
  if (iframe) {
    var btnClose = iframe.contentWindow.document.querySelector(".btnClose");
    btnClose.click();
  }
}
netlifyIdentity.on('login', function() {
  closeIdentityModal();
});
netlifyIdentity.on('logout', function() {
  closeIdentityModal();
});`

A permanent solution which doesn't rely on a class name would be more desirable however and I support @peterp's suggestion of creating a flag.
