### ISSUE TITLE
netlifyIdentity.currentUser() always returns null unless in on event handler

### ISSUE THREAD

**Issue by SteveALee** [netlify/netlify-identity-widget#355]
The only time I get a non null value back from `netlifyIdentity.currentUser()` is in an `.on()` handler when it is redundant as `user` is passed to the function anyway.

how do we get the current user info any other time? Other than doing a deep copy of the user object.

**Comment by jlengstorf** [comment]
@SteveALee the widget needs to be instantiated before it can return anything, so `.currentUser()` can't be called before the `init` event has completed

it should work as expected in event handlers or other functions that are called after the page has loaded, though

if you need the user on page load, using `.on('init')` is probably the more straightforward approach

hopefully that helps — let me know if you have additional questions!

**Comment by SteveALee** [comment]
@jlengstorf thanks. Would you believe I just figured that in a VERY long thread [with Jon Sully on the Netlify forums](https://community.netlify.com/t/gated-content-not-working-in-chrome-or-chredge/20640/96?u=slim). 

We were figuring out best place to put the token `refresh()` call. I'm using the global script in a plain paged site, he is using modules in SPA and I guess there are differences.

For your info here is my [identity widget abstraction](https://github.com/OpenDirective/TWAM-App/blob/master/src/js/netlify-identity.js#L67) 

> if you need the user on page load, using .on('init') is probably the more straightforward approach

Yes, I spent a time exploring the various state permutations including browser refresh to understand when `init` and `login` are raised. All very sensible :)
