### ISSUE TITLE
Add documentation link

### ISSUE THREAD

**Issue by bcomnes** [netlify/netlify-identity-widget#39]
It might be useful to add a documentation link regarding dev mode.

**Comment by bcomnes** [comment]
I strongly prefer readme docs for modules in general, but consistency is key here.  @verythorough any insight on what we should do?

**Comment by verythorough** [comment]
I think this repo is the best place for docs on this widget.  We also need a link to the repo in the widget demo. (Filing an issue now...)

**Comment by rafaelconde** [comment]
Can I close this issue with the recent addition of the GitHub link?
