### ISSUE TITLE
Dev mode UI/UX

### ISSUE THREAD

**Issue by bcomnes** [netlify/netlify-identity-widget#40]
We need to add some devmode ui elements:

- [ ] A gear button to open dev settings after they are set (https://github.com/netlify/netlify-identity-widget/pull/31)
- [ ] A bar in the widget that states you are operating in dev mode and what endpoint you are using.
- [ ] https://github.com/netlify/netlify-identity-widget/issues/68
- [ ] Disable/indicate providers won't work in devmode: https://github.com/netlify/netlify-identity-widget/issues/100 

UPDATE: The above plans may work, but fundamentally, we need to improve the devmode experience of this, and round off some common edge cases.

**Comment by erquhart** [comment]
An error message for localhost or 127.0.0.1 might be helpful, agreed.
