### ISSUE TITLE
Can you disable the "You are now logged in" window?

### ISSUE THREAD

**Issue by arronhunt** [netlify/netlify-identity-widget#511]
After logging in, the modal changes to "Logged in as {name}". Is there a way to disable it? I'm using react-router-dom and I have to use some hacks to manually dismiss the modal when the user is logged in, since the nav automatically takes them to their dashboard.

**Comment by Akdr** [comment]
Late on the ball but I had the same problem.

Try this:
```
    netlifyIdentity.on('login', (user) => {
      netlifyIdentity.close()
      console.log('User is now', user)
    })
```

**Comment by arronhunt** [comment]
@Akdr that’s the solution I ended up with. Feels a bit hacky but works well enough, going to close this issue.
