### ISSUE TITLE
Add high z-index to iframe inline styles

### ISSUE THREAD

**Issue by imorente** [netlify/netlify-identity-widget#67]
When there are any other fixed elements on the page, the iframe remains hidden under them.

**Comment by smakinson** [comment]
I see the same, here is what I am doing at the moment ( not much testing behind it as I'm just getting started ):

```
...
<div id="authModal" style="position:absolute; top:0; left: 0; z-index: 99999"></div>
</body>

elsewhere:

netlifyIdentity.init({
   container: '#authModal'
})
```

**Comment by bcomnes** [comment]
I belive this was fixed by https://github.com/netlify/netlify-identity-widget/pull/95
