### ISSUE TITLE
Local version Identity is associated with the wrong Netlify site

### ISSUE THREAD

**Issue by bdougie** [netlify/netlify-identity-widget#68]
I originally tested Identity locally shortly after the initial launch. I am now trying to add Identity a new site and noticed that my local version identity is still associated with kaldi template. https://gambler-fox-75602.netlify.com

The site I am attempting add identity to locally and test open-sauced.netlify.com (entirely different project)

Note that the error states a CORS issue below with a different URL. 

![screenshot 2017-09-25 10 58 22](https://user-images.githubusercontent.com/5713670/30823399-e250cf6e-a1e0-11e7-8bd3-7767c969a825.png)

I have since changed the name to kaldi-identity-access-test so, running the original project locally does not work.

### Steps to reproduce:
1. Add identity locally a site and enable dev mode
2. Add identity on a second site locally.
3. Confirm there is a 404 error

**Comment by bdougie** [comment]
@bcomnes how do I remove identity from being associated to the gambler-fox site on localhost:3000?

**Comment by bdougie** [comment]
Thanks @imorente, removing the netlifyUrl from localStorage fixes the CORS issue. `localStorage.removeItem("netlifySiteURL")`

I am not convinced this is a great experience for a user looking to use the identity service seriously.

I am now looking into mobx, since I do not any experience with it. I plan on adding some sort fo check to remove the netlifySiteURL on error now. Unless someone else has a better idea or direction for this. 

As a user, I expect to be prompted that the wrong URL is in my localStorage and given the opportunity to enter a new one.

**Comment by imorente** [comment]
Agreed that it's a not good experience! It obviously needs to get fixed (the only reason I told you about clearing local storage manually was to give you a workaround because you'd mentioned this was blocking you)

**Comment by bdougie** [comment]
Opening up the console remove the item from localStorage is not the bad experience -- getting the error in the console, with no indication on how to fix is the bad experience. Since the documentation points to this repository for more info, we can add a little more info to the README. #70

I am back in here looking to see if I can add a line to remove the URL on 404's. Though I think it might need to be added on the gotrue-js side, but I haven't gotten there yet.

**Comment by jlengstorf** [comment]
there is now a link in the modal to reset the localhost URL
