### ISSUE TITLE
Specify login or signup in .open method

### ISSUE THREAD

**Issue by bcomnes** [netlify/netlify-identity-widget#81]
It would be nice to be able to specify which page in the modal it opens to by passing `signup` or `login` to `netlifyIdentity.open(page)`

It would be added here: 

https://github.com/netlify/netlify-identity-widget/blob/05fcb1a3b77f2f7873adeeebd8378084507c7f02/src/netlify-identity.js#L17-L33

The only complexity would be handling cases when implementors call a signup page when signup is disabled.  I'm thinking we navigate back to login if this is the case.

cc @futuregerald 

UPDATE:  Gotrue supports redirects now, so this may play out slightly differently.

**Comment by hcavalieri** [comment]
Just to reinforce @bcomnes request, by having every confirmation URL pointing to the root of the domain, we are forced to include the Identity widget in the homepage's head, which is a real bummer for performance - according to [Pingdom](https://tools.pingdom.com/#!/cdkl2p/andorinhas.eco.br), the minified, gzipped version of it costs the user 46.8 precious kb... I know it might be a bit picky and I know you can always optimize other parts of your document, but we're talking about a quick solution here (hopefully).

Of course, we can ask tech-savvy users to copy the confirmation token and paste it on example.com/admin/, for example, and include the widget only in the admin page, but that's far from optimal.

Anywho, I lack the knowledge to implement it, but can help trying to figure out how to serve this option to the user, and, **as always, thank you so much for this amazing work**! 😄

**Comment by jlengstorf** [comment]
it's now possible to specify login or signup when opening the widget
