### ISSUE TITLE
Automatic autoconfirm for external providers

### ISSUE THREAD

**Issue by fgallaire** [netlify/netlify-identity-widget#84]
Automatic autoconfirm shouldn't be the default -at least- and the only -maybe- option for external providers as we rely on them to ensure all this stuff ?

**Comment by calavera** [comment]
It depends on the provider. The implementation is in https://github.com/netlify/gotrue. If the provider confirms emails, we assume that we can autoconfirm, if they don't, we don't autoconfirm.

**Comment by bcomnes** [comment]
Closing this issue as we do auto confirm providers that confirm email addresses.  Please reopen if there are unaddressed issues.
