### ISSUE TITLE
const user = netlifyIdentity.currentUser() return null

### ISSUE THREAD

**Issue by RioSatria** [netlify/netlify-identity-widget#89]
Whenever I try to call this function `const user = netlifyIdentity.currentUser();` it always return `null`

**Comment by bcomnes** [comment]
When the user is not logged in, `netlifyIdentity.currentUser()` will return `null`.  If the user is logged in, it will return the results of https://github.com/netlify/gotrue-js/blob/master/src/index.js#L115

Does the login process process complete successfully?

**Comment by bcomnes** [comment]
The other possible issue is checking to early.  `netlifyIdentity.on('init', user => console.log(user))` will give you the current on page init, if you are looking to get that information on page load.

**Comment by RioSatria** [comment]
Thank you very much!

`netlifyIdentity.on('init', user => console.log(user))` solve it and I get the information that I'm looking for through that.
